### ISSUE TITLE
Periodic crashes on version 1.1.4 Bannerlord. Incompatibility with some mods.

### ISSUE THREAD

**Issue by strazher** [Norbivar/RTSCamera#11]
Hello. I have 1.1.4 version. I'm using the 1.1.2 version of the mod. During battles, it periodically writes "the application faced a problem we need to collect necessary files to fix this problem". This rarely happens during normal battles. During sieges, this almost always happens, usually after 3-5 minutes.
I use several mods: Harmony v2.2.2.138; UIExtenderEx 2.8.0.0; ButterLib 2.8.0.0; MCM 5.7.1.0; Realistic Battle Mod 3.5.8.
Even if you turn it on only "Realistic Battle Mod", this error still appears.
If you turn it on only RTS Camera and RTS Command System, crashes do not happen.

**Comment by Norbivar** [comment]
Closing this, as I have not managed to find anything and it has not been reported as a widespread issue.
If it occurs on any newer builds, might reopen.
