### ISSUE TITLE
Crashed when starting a besige

### ISSUE THREAD

**Issue by gmatiash** [Norbivar/RTSCamera#12]
When starting a besiege it crashes. I did besiege on other occasions, but now it's not working for some reason. This is the only mod I have and if I try the exact same action without the mod works ok, and if I save after I started the besiege, save, exit, enable the mod and then load the save, it crashes when loading.

Here is the video: https://github.com/Norbivar/RTSCamera/assets/49596341/e36d9892-e3ea-4020-b9b4-b8c272a5938f

Save: 
[saveauto2.zip](https://github.com/Norbivar/RTSCamera/files/12022025/saveauto2.zip)

Versions: 
![image](https://github.com/Norbivar/RTSCamera/assets/49596341/0b6c8528-faba-4c34-b3f8-07ffbb116496)

If I enter a battle with another party, it gives an error when I select the Free camera option, but I can pause it without a problem.

**Comment by Norbivar** [comment]
Mate, you are running probably the beta branch version on the live bannerlord. If you get it from the steam workshop, it is for (most of the time) the LATEST beta branch.
You can try the 1.1.5 release from here, that is more likely to work.

**Comment by gmatiash** [comment]
It could be, but how can I use that version? I didn't saw any other RTS Camera from you: 
![image](https://github.com/Norbivar/RTSCamera/assets/49596341/f9eefa69-ef3f-417c-91db-4c3f6acd6652)
![image](https://github.com/Norbivar/RTSCamera/assets/49596341/31915327-9b3d-413c-9df1-b93aff6ba683)

**Comment by Norbivar** [comment]
Yeah, workshop can only handle a single version - and that is gonna be the latest, which is usually compatible with only the latest version - the version I am compiling for.

You can try the 1.1.2 one from here
https://github.com/Norbivar/RTSCamera/releases
If that also crashes, let me know and I'll take a look at uploading a proper one. :)

**Comment by gmatiash** [comment]
I removed the Steam version and manually copied the release that you provided and this error appeared when loading the game that was crashing:
![image](https://github.com/Norbivar/RTSCamera/assets/49596341/7caa40ff-190b-49af-8aa4-79ce4e368f36)
Here is the file:
![image](https://github.com/Norbivar/RTSCamera/assets/49596341/196ec92a-21d0-49fb-a8fd-bc4ef09df57d)

**Comment by Norbivar** [comment]
You might need to unblock the DLLs.

**Comment by gmatiash** [comment]
Can you please detail how that can be done so I can test it?

**Comment by Norbivar** [comment]
You can google it, but it's somewhere along the lines of "right click -> properties".
https://youtube.com/watch?v=1n2Rnib4FcY

**Comment by gmatiash** [comment]
That did the trick to prevent the lock error, but I am still having again "besiege" error: 
![image](https://github.com/Norbivar/RTSCamera/assets/49596341/a9c4e9bb-7cf7-4ca1-bdb0-4aff0a6e29ce)
Can I provide you with any further details?

**Comment by gmatiash** [comment]
Sorry, my mistake, now it works with this version

**Comment by Norbivar** [comment]
So does it seem to work now?

**Comment by gmatiash** [comment]
Yes, with the previous version it works
