### ISSUE TITLE
 XML error on Release RTS Camera v4.1.23+siege for Bannerlord v1.1.5 master

### ISSUE THREAD

**Issue by mapokl** [Norbivar/RTSCamera#15]
In updated version for 1.1.5+siege there is a xml error when starting the laucher. Laucher start fine, but mods are not visible.

The simple solution was copying xml from older 1.1.2 version. And it works ok.

![error](https://github.com/Norbivar/RTSCamera/assets/58701073/0eb0c028-0c4b-48a9-8d40-044a2a392529)

**Comment by Knightfall-dh** [comment]
same, but i just deleted "+siege" and it worked.

**Comment by Norbivar** [comment]
Upsie daisy, I'll look into it.

**Comment by Norbivar** [comment]
https://github.com/Norbivar/RTSCamera/releases/tag/unofficial-release-v4.1.23.0-for-bannerlord-v1.1.5
