### ISSUE TITLE
1.2.2 Lost effect in the middle of the mouse

### ISSUE THREAD

**Issue by LiZheGuang** [Norbivar/RTSCamera#17]
1.2.2 Lost effect in the middle of the mouse

**Comment by LiZheGuang** [comment]
Command System's middle mouse button, Charge has lost its effect

**Comment by Norbivar** [comment]
Command system had a clash in the AI code since 1.2.0.
Due to Bannerlord having their own attack-formation now, I realised it does not make sense to keep the mod intact, so it is just made to compile, but will not likely work.
Sorry.
