### ISSUE TITLE
Crashing when trying to use free cam

### ISSUE THREAD

**Issue by vojtech878** [Norbivar/RTSCamera#18]
Hello, as the title says after pressing L in battle and pressing the free cam button the game crashes. Im on game version 1.1.5

**Comment by Norbivar** [comment]
Hi there.
Could use some more information, especially a callstack.

**Comment by vojtech878** [comment]
Yeah sure, is this it?
https://report.butr.link/5CB228.html

**Comment by Norbivar** [comment]
Yeah, this should be useful.

**Comment by Norbivar** [comment]
It seems you are using the steam workshop version (or the latest here), that is really meant for the BETA branch (1.2.2 last time I updated).
Can you try the 1.1.5 version, from the releases here on github? Should be something like 4.1.23 I think.

**Comment by vojtech878** [comment]
ok, ill try. Just give me a sec my pc isnt the fastest :D

**Comment by vojtech878** [comment]
Ok, it worked, thanks and sorry, im kinda new to github :D

**Comment by Norbivar** [comment]
Oh, don't sweat it. :) Glad to help.
