### ISSUE TITLE
Crash when entering siege battle

### ISSUE THREAD

**Issue by Carsak** [Norbivar/RTSCamera#20]
How to reproduce

1. Become vassall
2. Kingdom start war
3. Lord start siege enemy castle
4. You join to battle

Get error 

Link
https://report.butr.link/CBB449

Dump:
[crashreport.zip](https://github.com/Norbivar/RTSCamera/files/12769429/crashreport.zip)

**Comment by Norbivar** [comment]
You are running a 1.2.2 version of the mod on 1.1.6. Of course it will crash. :D
