### ISSUE TITLE
Latest Beta 1.2.5 patch broke the mod :(

### ISSUE THREAD

**Issue by Quesant** [Norbivar/RTSCamera#24]
got a crash occuring when entering battle now :(
https://report.butr.link/C82E3E butr crash log, might help

**Comment by Norbivar** [comment]
I will take a look at it on next monday earliest. Thanks for the headsup!

**Comment by roflcakes3503** [comment]
i know you're just keeping up on the mod to have it updated for us, but i have to say that the game sucks without this mod. and i appreciate the hell out of you Norbivar for doing your best to keep this mod up to date. it is literally a completely different dynamic having this and being able to command troops.

**Comment by Norbivar** [comment]
Yeah, I myself cannot play Bannerlord without it either, although only for the misc features. 
I personally really live the simple slowmode/speed up of the game, quite handy on some looter fights when you don't want to use the auto-resolve to kill your troops.
The change character function is also my favourite.
But yeah, the mod in every way is literally "on demand", so everyone can use what they want from it and ignore the rest.
Appreciate the kudos as well!

Edit: recently I got into not just updating the mod, but adding small stuff as well. Currently I am experimenting with the "destination" flag objects of units, replacing them with something more visible.

**Comment by Quesant** [comment]
Yer a fookin legend mate, thank you! I agree, battles just feel so much better when commanding troops from above, it feels so clunky doing it from the normal camera angle

**Comment by roflcakes3503** [comment]
> Yeah, I myself cannot play Bannerlord without it either, although only for the misc features. I personally really live the simple slowmode/speed up of the game, quite handy on some looter fights when you don't want to use the auto-resolve to kill your troops. The change character function is also my favourite. But yeah, the mod in every way is literally "on demand", so everyone can use what they want from it and ignore the rest. Appreciate the kudos as well!
> 
> Edit: recently I got into not just updating the mod, but adding small stuff as well. Currently I am experimenting with the "destination" flag objects of units, replacing them with something more visible.

Legit the best possible thing to have during battles is the ability to slow down time. It's priceless

**Comment by Norbivar** [comment]
Seems to be fixed now, wasn't a big thing.

**Comment by Quesant** [comment]
your the best! thank you!!

**Comment by Norbivar** [comment]
Lovely!
