### ISSUE TITLE
The game crashes on launch and gives this error.

### ISSUE THREAD

**Issue by MachinTruc31** [Norbivar/RTSCamera#27]
![Capture d'écran 2023-12-13 113419](https://github.com/Norbivar/RTSCamera/assets/153726745/471adb7d-a039-434f-9649-885461bf1790)

Even removing all the mods and leaving only RTS Camera the game shows this error. help me ! ^^ (1.1.6)

**Comment by Norbivar** [comment]
Which version have you downloaded? (Link it)

**Comment by not-OP** [comment]
This worked for me:
https://www.nexusmods.com/mountandblade2bannerlord/mods/397?tab=description

**Comment by Norbivar** [comment]
Yeah, that is also something I wanted to suggest. You can also manually unblock it on Windows as well somewhere in properties for the .dll, but you got to look it up how.
