### ISSUE TITLE
OrderTroopItem.xml needs to be updated to match game changes

### ISSUE THREAD

**Issue by Rogue-Demon-King** [Norbivar/RTSCamera#29]
Some Constants and a new Widget piece have been added to the game OrderTroopItem.xml. Morale display is also missing in RTSCamera OrderTroopItem.xml.

**Comment by Norbivar** [comment]
I trust this was fixed by your PR https://github.com/Norbivar/RTSCamera/pull/30 ?

**Comment by Rogue-Demon-King** [comment]
Yes. Figured I might as well submit the edited file I use myself.

**Comment by Norbivar** [comment]
Alrighty, closing this one then, as I merged that.
