### ISSUE TITLE
Can't work on steamdeck

### ISSUE THREAD

**Issue by e04su3no** [Norbivar/RTSCamera#3]
I love this mod, it good work on PC, but can't enter the game on steamdeck, is it possible to make it work on Linux?  
Thanks

**Comment by e04su3no** [comment]
![下載](https://user-images.githubusercontent.com/128218934/230715260-03eb660e-52a2-43a1-85ed-8f8807081c1f.jpeg)

**Comment by Norbivar** [comment]
Ummm... To be honest, I have currently no way of reproducing this. Please post the lower part of the callstack as well, as that might be somewhat more informational, but I still can't promise anything.
