### ISSUE TITLE
i can't choose the mod in a launcher

### ISSUE THREAD

**Issue by klokta** [Norbivar/RTSCamera#35]
Hello i can't choose the mod in a launcher game, like it is transparent.
[Новий Документ Microsoft Word.docx](https://github.com/user-attachments/files/16424301/Microsoft.Word.docx)

![image](https://github.com/user-attachments/assets/b6de26bb-08dc-41f6-9464-cb4eb105eba4)

**Comment by commander1228** [comment]
hey bro I had the same thing, open the rts camera file you installed and theres another file inside of the same name, thats the one you want to actually put in the modules folder. hope this helps

**Comment by Norbivar** [comment]
Hey. Might not be apparent at first, but you need some dependencies:
- Harmony (for the code injection)
- UIExtenderEx (fixes UI issues)
