### ISSUE TITLE
Mod disables the "priority" selection button in Clan screen, for companion-led parties

### ISSUE THREAD

**Issue by sjblack2014** [Norbivar/RTSCamera#4]
This is for latest mod version, and game version 1.1.3
The button to select (neutral/aggressive/defensive) is unclickable with this mod installed.

**Comment by Norbivar** [comment]
That's interesting. 
Are you certain that the mod does it? Did you try to look at it with and without the mod?

**Comment by sjblack2014** [comment]
Yes, I disabled the mod and the button works again. Enabled it and it stops working. Later on I installed Harmony, UIExtenderEx, Butterlib (didn't have them at the time of my first post), and the button works with RTS Camera enabled.

**Comment by Norbivar** [comment]
That's good to know. I don't think the mod relies on any of them, so it's curious to hear that something helped it.

**Comment by Norbivar** [comment]
UIExtenderEx does fix something related to this. I am adding this as a dependency.
