### ISSUE TITLE
Crash on game startup

### ISSUE THREAD

**Issue by michaelDadurian** [Norbivar/RTSCamera#6]
Hey there, I have  v4.1.23.0 running on Bannerlord v1.1.3.  Not sure if this is an issue with the mod or what. Any input would be great!

![versions](https://user-images.githubusercontent.com/19558976/234753995-4e53f167-85fa-4b18-89cc-352d82fe0698.PNG)
![error](https://user-images.githubusercontent.com/19558976/234753999-79bd8d78-47dc-453d-afa2-25376463942b.PNG)
![mods](https://user-images.githubusercontent.com/19558976/234754154-15484e36-1d43-4a52-8407-f7177c9c54db.PNG)

**Comment by Norbivar** [comment]
Hmm. I definitely seen these kind of errors on the Nexus page, and I think it had something to do with the binary versions.
I personally keep the "dependent" versions (= the versions the launcher is complaining for) correct, as in the given mod versions were used to and compiled for their designed versions.  Lemme' check.

EDIT 1: It seems to work for me, so first, I'd try maybe unblocking the DLLs?

**Comment by pyroo4ever** [comment]
there is no bin folder
