### ISSUE TITLE
Unhandled Exception when creating/loading savegame

### ISSUE THREAD

**Issue by neekometria** [Norbivar/RTSCamera#8]
### The game throws a error when trying to open a sandbox/campaign save
[lutris-log.txt](https://github.com/Norbivar/RTSCamera/files/11435493/lutris-log.txt)

### Steps to reproduce
1. activate both modules on launcher;
2. start game;
3. select "sandbox", "campaign" or saved game;
4. profit...

### System
Game version: 1.1.3

OS: Linux Mint 21.1
CPU: Phenom II x6 1055t
RAM: 12GB
GPU: NVidia GTX 650
Proton: Lutris GE Proton 8_4x64

**Game opens with no problem without this module**

**Comment by neekometria** [comment]
Note: works fine in custom battle

**Comment by Norbivar** [comment]
Cannot find text. Did you install the proper full directory?
